services:
  - type: web
    name: aura-ai-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: ALLOWED_FILE_TYPES
        value: "image/jpeg,image/png,image/gif,audio/mpeg,audio/wav"
      - key: FRONTEND_URL
        value: "https://your-frontend-domain.com"
    healthCheckPath: /health
    autoDeploy: true